### ISSUE TITLE
Receive-MgaOauthToken function ParameterSetName 'RedirectUri' and 'Redirecturi' character-case issue

### ISSUE THREAD

**Issue by envegter** [baswijdenes/Microsoft.Graph.API#14]
Hi Bas,

i just tried connect-mga using the RedirectUri parameter. When doing so with the current version 0.0.2.7 I get the error that the parameterset could not be resolved. It turns out that the name used in the ParameterSetName is actually case-sensitive. In two places in the module-function Receive-MgaOauthToken the ParameterSetName is Redirecturi instead of RedirectUri.
After changing that case and reloading the module it works.

Rgds,
Eric

**Comment by baswijdenes** [comment]
Thanks! I've never known that ParameterSets were case sensitive.... Should have tested EVERYTHING before pushing to prod ;-)

**Comment by baswijdenes** [comment]
PS: I updated the module in Github & PSGallery ;-)

**Comment by envegter** [comment]
Dank je!
Ik ben nog wat aan t herschrijven in de functies om meerdere document libraries te ondersteunen. Je gebruikt nu /drive/ waardoor je de default document library/list aanspreekt. Als er meerdere libraries zijn dan upload je naar /drives/{drive-id}/.
Ik heb een parameter -libraryName met default ‘documents’ waarde.
Na de mga-get $PSURL stel ik de URL samen om de Drives uit te lezen en te filteren op die van de naam van de gevraagde library.
Dat id komt dan als parameter in de URL voor de upload of download request.

Ik zal denk ik een pull request sturen als ik m’n eigen branche maak of ik stuur de aanpassingen wel door als je wilt. :)

Groet
Eric

Verstuurd vanaf mijn iPhone

Op 12 mei 2022 om 11:24 heeft Bas Wijdenes ***@***.***> het volgende geschreven:

﻿

PS: I updated the module in Github & PSGallery ;-)
