### ISSUE TITLE
commands missing

### ISSUE THREAD

**Issue by andrew-holowaty** [baswijdenes/Microsoft.Graph.API#16]
I followed the directions at https://baswijdenes.com/get-azuread-guest-users-lastlogin-for-stale-accounts-powershell/#Which_property_comes_closest_to_the_LastLogin_property.  When I use powershell in ISE with PS version 5.1.19041.1682, I do not see commands Get-AzureADUsers.  I received the following error:
PS C:\WINDOWS\system32> Get-AzureADUsers
Get-AzureADUsers : The term 'Get-AzureADUsers' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of 
the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-AzureADUsers
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzureADUsers:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I was able to run Connect-Mga -ApplicationID with params and do everything else.  Looking forward to being able to get the last login for users. Please help!

**Comment by baswijdenes** [comment]
Hey Andrew, did you also install the module [Optimized.Mga.AzureAD](https://www.powershellgallery.com/packages/Optimized.Mga.AzureAD/0.0.0.0)? 
this is a submodule that will also install the module you installed now :-)

**Comment by baswijdenes** [comment]
Closing issue with my response above
